# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go
on:
  workflow_dispatch:
jobs:
  build:
    name: Build
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: ${{ github.event.repository.name }}-windows-amd64.exe
            install_deps: ""
            env_vars: GOOS=windows GOARCH=amd64 CGO_ENABLED=0
            build_args: -a -ldflags '-extldflags "-static" -s -w' -trimpath
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone Code
        run: |
          git clone https://github.com/shadow1ng/fscan.git
          cd fscan
          git checkout tags/v2.1.0
          go mod tidy
  
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
  
      - name: Install dependencies
        run: ${{ matrix.install_deps }}
  
      - name: Build
        run: ${{ matrix.env_vars }} go build ${{ matrix.build_args }} -o dist/${{ matrix.artifact_name }}
        working-directory: fscan
  
      - name: Upload files to Artifacts
        uses: actions/upload-artifact@v5.0.0
        with:
          name: ttttt
          path: |
            fscan/dist/*

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'release'
        with:
          files: |
            fscan/dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
